"""thoughts updated_at

Revision ID: d89e62264512
Revises: ea0b881b08a8
Create Date: 2025-06-11 16:00:23.692453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd89e62264512'
down_revision: Union[str, None] = 'ea0b881b08a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thoughts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.drop_index(op.f('thoughts_embedding_idx'), table_name='thoughts', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('thoughts_embedding_idx'), 'thoughts', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('thoughts', 'updated_at')
    # ### end Alembic commands ###
